[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
evm_version = 'london'
optimizer = true
optimizer_runs = 200
use_literal_content = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
saigon = "https://saigon-archive.roninchain.com/rpc"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
