[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.17"
optimizer = true
optimizer_runs = 200
use_literal_content = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
	"@openzeppelinupgrade/=lib/openzeppelin-contracts-upgradeable/contracts/",
]

[rpc_endpoints]
saigon = "https://saigon-archive.roninchain.com/rpc"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
